services:
  easybot.full:
    build:
      context: ..
      dockerfile: full/Dockerfile
    container_name: easybot
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "26990:26990"
    volumes:
      - ~/easybot/data:/app/appdata
      - ~/easybot/logs:/app/logs
